### ISSUE TITLE
merchant-facing camera for poynt

### ISSUE THREAD

**Issue by jadir-junior** [Scandit/barcodescanner-sdk-cordova#104]
I have a mobile poynt, there are two cameras (merchant-facing, and customer-facing). my customer-facing camera is ok, but merchant-facing camera is left-side, how I can turn in right directon this camara?

**Comment by biasmv** [comment]
Hi @jadir-junior, 

if I'm understanding you correctly, the preview image for the user-facing (selfie) camera is mirrored (flipped). 

We have a private option to enable vertical preview mirroring in 5.5.0BETA1. This option is not present in previous version, so make sure to use the latest beta available on our website. Could you test if enabling this option solves the issue for you? You can enable it like this:

```
ScanSettings scanSettings = ...';
scanSettings.setProperty("mirror_preview_vertically", true);
```

Note that this will enable preview mirroring for both cameras, so this will screw up the preview for the customer facing camera. If this solves the issue for you, we will modify the SDK to allow the preview mirroring to be controlled independently for the two cameras.

**Comment by jadir-junior** [comment]
this dont solve my problem

**Comment by biasmv** [comment]
Too bad. Since this sounds like a device specific issue, please get in touch with support@scandit.com. Please make sure to include the exact model name of the device you are using as well as used SDK and Android versions.

**Comment by jadir-junior** [comment]
I think I'm wrong, I dont tried with version 5.5.0BETA1. I'm try again!

**Comment by biasmv** [comment]
Just realized that the lines above wont' work for cordova (these are the calls required for native android). For JavaScript, you will have to use the following:

```js
var scanSettings = ...;
scanSettings.properties = {
   'mirror_preview_vertically' : 1
};
```

**Comment by jadir-junior** [comment]
That working just in front camera, the back camera still the same, properties have any other properties?

**Comment by jadir-junior** [comment]
There are anything that can I rotation the camera?

**Comment by biasmv** [comment]
Just to get this straight: before setting 'mirror_preview_vertically' the front camera was mirrored incorrectly, the back camera was OK, but after setting 'mirror_preview_vertically' the front camera was OK, but the back camera was not OK?

**Comment by jadir-junior** [comment]
No, before setting up 'mirror_preview_vertically' the front camera was OK and the back was turned to the left, After setting 'mirror_preview_vertically' the front camera was reversed and did not change any state of the camera back camera.

**Comment by biasmv** [comment]
This sounds like a device-specific issue. Would it be possible to forward this request to support@scandit.com, including pictures of how the camera preview is rotated/flipped in your case? We will then try to coordinate getting the device in our lab, and/or advice on additional steps.

**Comment by jadir-junior** [comment]
Thank you so much for the help.

I can rotate the camera with the setting with

settings.properties = {
      "sensor_orientation_override_back": 0
    }

that value can be 0, 90, 180, 270
