### ISSUE TITLE
Text recognition settings

### ISSUE THREAD

**Issue by Coolcat13** [Scandit/barcodescanner-sdk-cordova#120]
Hi there, currently trialing the plugin - I am unable to figure out how to set the text recognition settings, can you help? Here is what I am using but it doesn't work, nothing happens (the scanner shows but text is not recognised). I think I might need to set TextRecognitionSettings but no idea how to do that - the documentation does not have an example. Thanks in advance,

var settings = new Scandit.ScanSettings();
settings.RecognitionMode = "TEXT";
var picker = new Scandit.BarcodePicker(settings);
picker.show(success, null, failure);
picker.startScanning();

**Comment by moritz-scandit** [comment]
Hi,

The text recognition settings have to be set on the normal scan settings (https://docs.scandit.com/stable/phonegap/class_scandit_1_1_scan_settings.html#a2b263d09add8839263a8e23cef97c18b) so it would look something like:

```
var textRecognitionSettings = new Scandit.TextRecognitionSettings();
var settings = new Scandit.ScanSettings();
settings.textRecognition = textRecognitionSettings;
```

You can find the properties of the text recognition settings at https://docs.scandit.com/stable/phonegap/class_scandit.html#class_scandit_1_1_text_recognition_settings

Also make sure you write `recognitionMode` correctly, it starts with a lower case `r`

Please be aware that you need a license that has text recognition enabled to be able to use it, the default one doesn't allow it.

**Comment by Coolcat13** [comment]
Thanks - this is what I have now, but it's still not working (no error) - is it correct? Is OCR disabled on a trial license?

var settings = new Scandit.ScanSettings();
settings.recognitionMode = "TEXT";

var textRecognitionSettings = new Scandit.TextRecognitionSettings();
settings.textRecognition = textRecognitionSettings;
settings.textRecognition.regex = "([0-9]{4,5})";
settings.textRecognition.characterWhitelist = "01234567890";
settings.textRecognition.areaPortrait = new Scandit.Rect(0, 0.4, 0.9, 0.1);

var picker = new Scandit.BarcodePicker(settings);
picker.show(success, null, failure);
picker.startScanning();

Thanks

**Comment by moritz-scandit** [comment]
it's odd that you don't see any error, you should be seeing one as ocr is indeed disabled for trial licenses. If you would like to test it out please contact us at support@scandit.com

**Comment by Coolcat13** [comment]
I have reached out to support via your website. Thanks.
