### ISSUE TITLE
ISBN10 often require X at the end - no way to manually do this currently

### ISSUE THREAD

**Issue by kylex** [Scandit/barcodescanner-sdk-cordova#146]
When using the scanner and needing to manually enter in a number at the top, some ISBNs require an X as the check digit. Currently the keypad does not allow for that, nor does it let us switch to a normal keyboard.

**Comment by lucatorella** [comment]
You are right, we don't support that yet. Can you please write support@scandit.com?

**Comment by kylex** [comment]
I've just sent an email detailing this issue.

**Comment by moritzhartmeier** [comment]
Fixed in #165, will be released with 5.9.0
