### ISSUE TITLE
Scanner Cancel/Destroy after effects

### ISSUE THREAD

**Issue by sandisototo** [Scandit/barcodescanner-sdk-cordova#202]
Using the **cordova** and **web** SDKs on our angular 4+ app.

The issue we are experiencing is the ability the run dynamic css/javascript effects on the DOM after one of the above mentioned functions have been executed.

One typical example is:

 - Using https://material.angular.io/components/stepper

   - In step 1, I want to scan a barcode then move to step 2 without any user interaction.

      **Expected behavior:**

       Closes/kills the scanner/camera then moves/display next step(step 2)

      **Actual behavior:** 

       Closes/kills the scanner then freezes on the active step until I click anywhere on the page then it          continues to the next step.

**Functions used to kill the scanner:**

Web: https://docs.scandit.com/stable/web/classes/barcodepicker.html#destroy
Cordova: https://docs.scandit.com/stable/phonegap/class_scandit_1_1_barcode_picker.html#a02d5fa6b14e221f3012a794b905be166

Please help.

**Comment by moritzhartmeier** [comment]
Hi @sandisototo 

Your issue somehow fell through the cracks on our end, is this still an issue that needs investigation?
