### ISSUE TITLE
Orientation not working on iOS

### ISSUE THREAD

**Issue by alexa2690** [Scandit/barcodescanner-sdk-cordova#227]
We have tried to lock the camera from rotating.
We have tried either:
- by setting the property orientations 
barcodePicker.orientations = [Scandit.BarcodePicker.Orientation.Portrait]
or 
- by using the setOrientations function
barcodePicker.setOrientations([Scandit.BarcodePicker.Orientation.Portrait])
Neither of them are taken into account and as a result the camera keeps rotating. 
Has anyone bumped into this? 

We are using the latest scandit plugin for phonegap. The application is built using ionic 3.

**Comment by moritzhartmeier** [comment]
Any issue with the orientations should have been fixed with #221 which is part of the latest 5.11 release. The previous 5.10 release did not contain this fix yet. Are you sure that you are on the latest version which is 5.11.1?

**Comment by alexa2690** [comment]
I grabbed the latest version and it works. Thank you!
