### ISSUE TITLE
setMargins does not take into account notch devices

### ISSUE THREAD

**Issue by alexa2690** [Scandit/barcodescanner-sdk-cordova#228]
I'm not sure if this is a bug or a feature, but we are using continuous scanning in our application and the camera is displayed on the screen using setMargins function. It works on all devices except for the devices that have notch. If anyone has bump into this issue and has a solution on how to take into account the notch please let me know.

In the application we have a header section and the scanner is using the below code to display the camera:
 barcodePicker.setMargins(new Scandit.Margins("0", "86px", "0", "60%"), null, 0); 
//86px is header height, on notch devices the header becomes bigger.
 barcodePicker.continuousMode = true;

**Comment by moritzhartmeier** [comment]
Hi there! Is this about Android or iOS devices? Or both?

**Comment by alexa2690** [comment]
Hello! We are deploying only to iOS devices.

**Comment by petradonka** [comment]
Hey @alexa2690!

If I understand it right, the margins just don't take into account the notch, so the picker is not at the right position.
Taking the notch (or any other safe area) into account for margins is currently not a feature of our Cordova plugin, so you'll need to manually get the size of the notch and add it to your top margin.

Let me know if this works for you.

Cheers,
Petra
