### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by artuska** [Scandit/barcodescanner-sdk-cordova#237]
Please update your NPM package to the latest version. https://www.npmjs.com/package/com.mirasense.scanditsdk.plugin is stuck on 5.7.2 version

**Comment by petradonka** [comment]
The Scandit Cordova plugin is *not* published to NPM, the package you linked is from a third party and we have no influence over it.

**Comment by artuska** [comment]
Oh, 'cmon, can you just publish it to NPM, is that so hard?

**Comment by petradonka** [comment]
You can always contact support@scandit.com with feature requests 🙂
