### ISSUE TITLE
ERROR ReferenceError: Scandit is not defined (Cordova - Angular)

### ISSUE THREAD

**Issue by lambirou** [Scandit/barcodescanner-sdk-cordova#241]
The Scandit class is indefinite, while I followed the installation steps correctly.
My project is under:
- Angular: 7.2.0
- Typescript: 3.2.2
- Cordova: 9.0.0

**Comment by petradonka** [comment]
Hi @lambirou,

Could you give us some more information about when and how you're trying to access `Scandit` the first time in your application?
Are you able to reproduce the issue also with our [simple](https://github.com/Scandit/barcodescanner-sdk-cordova/tree/release-5.11/samples/simple/www) or [extended](https://github.com/Scandit/barcodescanner-sdk-cordova/tree/release-5.11/samples/extended) samples?

**Comment by lambirou** [comment]
```js

import { Injectable } from "@angular/core";

export class ScanResult {
  text = "";
  cancel = false;
  format:
    | "QR"
    | "DATA_MATRIX"
    | "UPCE"
    | "UPCA"
    | "EAN8"
    | "EAN13"
    | "CODE128"
    | "CODE39"
    | "CODE93"
    | "CODABAR"
    | "ITF"
    | "RSS14"
    | "R";
}

@Injectable({
  providedIn: "root"
})
export class ScannerService {
  private scanner: any;

  constructor() {
    console.log(Scandit);
  }

  /**
   * Initialize the barcode scanner.
   */
  init(appKey: string) {
    Scandit.License.setAppKey(appKey);

    const settings = new Scandit.ScanSettings();
    settings.setSymbologyEnabled(Scandit.Barcode.Symbology.EAN13, true);
    settings.setSymbologyEnabled(Scandit.Barcode.Symbology.UPC12, true);
    settings.setSymbologyEnabled(Scandit.Barcode.Symbology.EAN8, true);

    this.scanner = new Scandit.BarcodePicker(settings);
    this.scanner.setMargins(
      new Scandit.Margins("0%", "0%", "0%", "50%"),
      new Scandit.Margins("0%", "0%", "0%", "50%"),
      0
    );
  }

  /**
   * Open the barcode scanner.
   */
  scan(options: any) {
    return new Promise((resolve, reject) => {
      this.scanner.show(
        session => {
          const data = new BarcodeScanResult();
          data.cancel = false;
          data.format = session.newlyRecognizedCodes[0].symbology;
          data.text = session.newlyRecognizedCodes[0].data;

          resolve(data);
          session.stopScanning();
        },
        null,
        error => reject(error)
      );
      this.scanner.startScanning();
    });
  }

  /**
   * Start the scanner
   */
  start() {
    this.scanner.startScanning();
  }

  /**
   * Closing the scanner
   */
  close() {
    this.scanner.cancel();
  }
}
```

**Comment by petradonka** [comment]
I can't really see much about the application lifecycle based on the code snippet you sent, can you confirm that you make sure that you're only accessing Cordova related functionality after the `deviceready` event has been fired?

We handle this explicitly in the extended sample, as you're using Angular, you'd need to do something similar. Take a look at our solution here: https://github.com/Scandit/barcodescanner-sdk-cordova/blob/release-5.11/samples/extended/src/app/main.ts#L7-L22

You could also try logging something to the console when the `deviceready` event fires to make sure that already happened before you try to access the `Scandit` namespace.

**Comment by lambirou** [comment]
A big thank you to you @petradonka , your support allowed me to solve my problem.

**Comment by lambirou** [comment]
Is there a way to add elements (buttons ...) over the camera?

**Comment by petradonka** [comment]
Unfortunately currently there's no way to do that.

The possibility to show HTML elements over the camera preview will be part of the next major version of the Scandit Cordova plugin, expected to be out in Q4 2019.

**Comment by lambirou** [comment]
Ok we are looking forward to this next release.
Thanks for the support.

**Comment by petradonka** [comment]
Glad we could help you resolve the issue!

**Comment by petradonka** [comment]
@florindobre-scandit, could you take a look at this?

**Comment by ScanditSupport** [comment]
Hi @girish-fuluskar,

My apologies for the inconvenience. 

Please note that our Cordova SDK contains TS typings now, and so you do not have to declare the Scandit namespace anymore. 

In case your issue persists, please reach out directly to us

[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)

**Comment by fffrikkie** [comment]
@girish-fuluskar Were you able to fix the problem? I am sitting with the exact same thing

**Comment by ScanditSupport** [comment]
Hi @fffrikkie.

I am sorry to hear that.

Please note that our Cordova plugins are meant to be used on mobile device as we rely on the `deviceready` event to be able to expose the API. When trying to run it in a browser, our API won't not available. 

Would you mind reaching out directly to us so that we can help you with your issues? 
[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)

**Comment by girish-fuluskar** [comment]
> @girish-fuluskar Were you able to fix the problem? I am sitting with the exact same thing

Hi,

I solved this issue by executing it on physical device.
