### ISSUE TITLE
BarcodePicker dissapears right after showing without any errors 

### ISSUE THREAD

**Issue by abondarenko** [Scandit/barcodescanner-sdk-cordova#246]
Hi,

I've tryied sample code and can't get it work.
I've changed only type of barcodes I want to scan.

```
      Scandit.License.setAppKey('my license');

      var settings = new Scandit.ScanSettings();
      settings.setSymbologyEnabled(Scandit.Barcode.Symbology.CODE128, true);

      // Instantiate the barcode picker by using the settings defined above.
      var picker = new Scandit.BarcodePicker(settings);

      const success = function(session) {
        alert('Scanned ' + session.newlyRecognizedCodes[0].symbology + ' code: ' + session.newlyRecognizedCodes[0].data);

        // If you are using continuous scanning you might want to stop here. Please note that
        // you will have to use session.stopScanning()/session.pauseScanning() instead of the
        // corresponding method on the picker. This will avoid a race condition and immediately stop
        // the scanning process after the success callback has finished executing.
        session.stopScanning();
      };

      const manual = function(content) {
        console.log('Manual: ' + content);
      };

      const failure = function(error) {
        console.log('Failed: ' + error);
      };

      picker.show(success, manual, failure);

```

Picker is opened, but is dissapeared in fraction of second.

I ran the app in the following environment:
com.mirasense.scanditsdk.plugin: 5.12.1
cordova 6.5
iOS 13.1.2

**Comment by lucatorella** [comment]
yes, unfortunately this is an issue when you use Xcode 11 and deploy to iOS 13, we actually fixed it yesterday. It will be released soon as part of 5.13. This is the MR that fixed it: https://github.com/Scandit/barcodescanner-sdk-cordova/pull/245

**Comment by abondarenko** [comment]
Hi!
@lucatorella, when are you going to release it?

**Comment by petradonka** [comment]
We're expecting the stable release of 5.13 later this month, while you will be able to already access the beta release this week.

**Comment by abondarenko** [comment]
Thank you!

**Comment by abondarenko** [comment]
Any news about beta?

**Comment by lucatorella** [comment]
5.13.0BETA2 is already available from the Scandit dashboard. The source code is here GitHub in the 5.13 branch.

**Comment by abondarenko** [comment]
Nice, will try it. Thanks!

**Comment by abondarenko** [comment]
It works. Thanks!
This issue can be closed, I believe.

**Comment by lucatorella** [comment]
I'm glad the fix worked for you. Thanks for getting back.
