### ISSUE TITLE
How can I precisely select one barcode among many?

### ISSUE THREAD

**Issue by abondarenko** [Scandit/barcodescanner-sdk-cordova#248]
I want to scan the only single barcode among many and found the following guide in FAQ:

>  - Start the scanner in paused mode (camera preview on but not scanning) and:
>  
>      1. Use our laser UI (you will find it in the ScanOverlay class of your platform in our documentation) to give the user a precise indication of where he should scan.
>      2. Restrict the scanning area (you will find a guide about it for your platform in our documentation) to a thin line in the center of the screen.
>  
>  - Add a “Scan” button to [resume the scanner] on user tap. When the scanner is active, the button can be greyed out and display “Scanning”.
>  
>  - When a barcode is scanned, [pause] or [stop] the scanner. This will ensure that you are not scanning any other codes.
> 

But I dont know how to add "Scan" button to barcode picker UI and can't find anything in documentation.

I've tried also Multiscan feature, but there is no possibility to select barcode interactively.

**Comment by moritzhartmeier** [comment]
Hi @abondarenko 

Our 5.x cordova plugin is limited in the way that you are unable to add buttons on top of it (this is something that will be addressed in our new 6.x plugin, but only with version 6.2 at the end of the year, so you can't move to that yet). The option you have in 5.x is that you [add constraints](https://docs.scandit.com/stable/phonegap/class_scandit_1_1_barcode_picker.html#a26599ca68d6f5e38555485535e71d8ed) which will make the scanner not fill 100% of the screen. That way you can place a button in the area where the scanner isn't. So for example you can set a bottom constraint of 20% to show the bottom 20% of the webview below where you can place a button that starts/pauses/stops the scanner.

Multiscan is also something that is limited in the 5.x plugin, a nice Cordova solution there will only be available with 6.3.

I hope that helps, if you have follow-up questions, just ask.
