### ISSUE TITLE
Add support for Capacitor

### ISSUE THREAD

**Issue by nic-craig** [Scandit/barcodescanner-sdk-cordova#249]
Hi, 

Would it be possible to add support as a Capacitor plugin so that we can use in a PWA on Browser and Ionic app?

Thanks

**Comment by petradonka** [comment]
Hi @nic-craig,

It'd be great if you'd get in touch with us over support@scandit.com, so our product team can evaluate and prioritize this!

Cheers,
Petra

**Comment by nic-craig** [comment]
Hi Petra, 

I have contacted the team so will close this. 

Thanks
