### ISSUE TITLE
Resize scanner when keyboard opens

### ISSUE THREAD

**Issue by akshayajeevan** [Scandit/barcodescanner-sdk-cordova#262]
Hi,

We are migrating the scandit plugin from 5.0 to 5.13.3. 
The scanner is shown on 50% of the screen and other 50% shows an input box to enter value manually.  When keyboard opens for the input box, the app webview shrinks but the scanner view is not shrinking or resizing accordingly. This makes the input box hide behind scanner. 

This behavior is perfect in 5.0 version but somehow not working for 5.13.3

Can anyone help me here.

**Comment by petradonka** [comment]
Hi @akshayajeevan,

Our support team will be able to help you best with this issue, please reach out to them at support@scandit.com.

Cheers,
Petra

**Comment by akshayajeevan** [comment]
I resized the scanner using higher margins in `setMargins()` when keyboard opens and back to lower margins when keyboard closes. This works fine when scanner is running.

**Comment by petradonka** [comment]
That's great to hear! Thanks for letting us know this worked out for you.
