### ISSUE TITLE
setTorchEnable only works when view changes

### ISSUE THREAD

**Issue by lucasfeliciano** [Scandit/barcodescanner-sdk-cordova#50]
Hello there,

Since my last issue I made huge progress.
Now I have a Scandit component working on react-native and I'm implementing the feature of passing the Scandit settings through the react-native compoment example:

`<Scandit ean13={true} />`

The example above enable Scandit to scan ean13 codes and it is working since this is a setting from ScanditSettings.

When I reached a point to enable/disable the torch button using the same approach the scanner start with no torch button but when I the app go to landscape mode and then go back to portrait mode the button appears.

This is what I have:

``` java
//RCTScanditManager.java
package com.rctscandit;

import com.facebook.react.bridge.LifecycleEventListener;
import com.facebook.react.uimanager.SimpleViewManager;
import com.facebook.react.uimanager.ThemedReactContext;
import com.facebook.react.uimanager.annotations.ReactProp;
import com.scandit.barcodepicker.ScanSettings;
import com.scandit.recognition.Barcode;

import javax.annotation.Nullable;

public class RCTScanditManager extends SimpleViewManager<RCTScanditView> implements LifecycleEventListener {

    public static final String REACT_CLASS = "RCTScandit";
    private RCTScanditView mScanditView;
    private ScanSettings settings = ScanSettings.create();

    @Override
    public String getName() {
        return REACT_CLASS;
    }

    @Override
    public RCTScanditView createViewInstance(ThemedReactContext context) {
        context.addLifecycleEventListener(this);

        mScanditView = new RCTScanditView(context, this.settings);
        return mScanditView;
    }

    @ReactProp(name = "ean13")
    public void setEan13(RCTScanditView view, @Nullable Boolean ean13) {
        this.settings.setSymbologyEnabled(Barcode.SYMBOLOGY_EAN13, ean13);
        view.applyScanSettings(this.settings);
    }

    @ReactProp(name = "upca")
    public void setUpca(RCTScanditView view, @Nullable Boolean upca) {
        this.settings.setSymbologyEnabled(Barcode.SYMBOLOGY_UPCA, upca);
        view.applyScanSettings(this.settings);
    }

    @ReactProp(name = "qr")
    public void setQr(RCTScanditView view, @Nullable Boolean qr) {
        this.settings.setSymbologyEnabled(Barcode.SYMBOLOGY_QR, qr);
        view.applyScanSettings(this.settings);
    }

    @ReactProp(name = "torch")
    public void setTorch(RCTScanditView view, @Nullable Boolean torch) {
        view.getOverlayView().setTorchEnabled(torch);
    }

    @Override
    public void onHostResume() {
        this.mScanditView.startScanning();
    }

    @Override
    public void onHostPause() {
        this.mScanditView.stopScanning();
    }

    @Override
    public void onHostDestroy() {

    }
}
```

``` java
//RCTScanditView.java
package com.rctscandit;

import android.content.Context;

import com.facebook.react.bridge.Arguments;
import com.facebook.react.bridge.ReactContext;
import com.facebook.react.bridge.WritableMap;
import com.facebook.react.modules.core.RCTNativeAppEventEmitter;
import com.scandit.barcodepicker.BarcodePicker;
import com.scandit.barcodepicker.OnScanListener;
import com.scandit.barcodepicker.ScanSession;
import com.scandit.barcodepicker.ScanSettings;


public class RCTScanditView extends BarcodePicker implements OnScanListener {
    RCTScanditView(Context context, ScanSettings settings){
        super(context, settings);
        this.setOnScanListener(this);
    }

    @Override
    public void didScan(ScanSession scanSession) {
        WritableMap event = Arguments.createMap();
        event.putString("code", scanSession.getNewlyRecognizedCodes().get(0).getData());
        ReactContext reactContext = (ReactContext) getContext();
        reactContext.getJSModule(RCTNativeAppEventEmitter.class).emit(
                "onScan",
                event);
    }
}
```

Any idea on this one?

**Comment by moritz-scandit** [comment]
I assume in this case you are calling setTorch at some point? What happens if you don't call it, what if you remove the function entirely? The reason why I ask is that the torch should be visible by default so if you do nothing it should be visible. What strikes me as weird is that you have everything marked as @Nullable while all those values should be @Nonnull, but I doubt that has any influence here.

**Comment by lucasfeliciano** [comment]
@moritz-scandit If I don't call the setTorch I have the same behaviour as if I call it as true.
It doesn't appear at first but when I go to landscape mode and then go back to portrait mode It appear.

If I call it as false, I have the expected behaviour: no torch button at all.

About the annotations, it doesn't matter in this case because it is never been called by me as null, but you are right and will change it.

**Comment by bulkyracehorse512** [comment]
@lucasfeliciano how are you signaling events in JS. In the react native component that contains the Android View, I have included: 
`  componentWillMount() {
    DeviceEventEmitter.addListener('onScan', function(e: Event) {
      console.log("Check onScan", e.nativeEvent, e)
    });
  }`
as modeled in the RN documentation, but aside from seeing the "Scandit" view, there appears to be no communication with JS as to the barcodes that are scanned.  I would ideally like to communicate with my API via JS and not through android.  

is your `RCTScanditView.java` file the only instance where you're emitting an event?

Thanks!

**Comment by swenner** [comment]
@lucasfeliciano The upcoming SDK version 5.5 has official support for React Native. Feel free to try it out:
https://github.com/Scandit/barcodescanner-sdk-react-native
