### ISSUE TITLE
Could not open driver egl_gallium.so

### ISSUE THREAD

**Issue by AbrahamHan** [Scandit/barcodescanner-sdk-cordova#62]
libEGL warning: Could not open driver /usr/lib/arm-linux-gnueabihf/egl/egl_gallium.so (libOpenVG.so.1: cannot open shared object file: No such file or directory)
libEGL warning: DRI2: failed to authenticate
my environment is Nvidia Jetson TK1(armhf)

**Comment by biasmv** [comment]
Could you provide more context for this warning? Based on the hardware you are running on, I'm assuming that you are using the linux SDK. If so, could you direct your question to support@scandit.com, rather than here? This project is for the cordova plugin only.
